version: "2"

services:
  etl_zoo:
    image: wurstmeister/zookeeper
    container_name: etl_zoo
    ports:
      - "2181:2181"
  etl_kafka:
    image: wurstmeister/kafka
    container_name: etl_kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: etl_kafka
      KAFKA_ZOOKEEPER_CONNECT: etl_zoo:2181
      KAFKA_CREATE_TOPICS: "IN:1:1,OUT:1:1"
    depends_on:
      - etl_zoo
  etl_run:
    image: openjdk:8
    container_name: etl_run
    restart: always
    volumes:
      - ./kafka-etl/kafka-etl-run/src/main/resources/configuration.json:/config.json:z
      - ./kafka-etl/kafka-etl-run/target/kafka-etl-run-runnable.jar:/kafka-etl-runnable.jar:z
      - ./kafka-etl/kafka-etl-core/target/kafka-etl-core-1.0.0-SNAPSHOT.jar:/transformer.jar:z
    command: /bin/bash -c "java -jar /kafka-etl-runnable.jar -conf /config.json -classpath /transformer.jar:* && while true; do echo \"debug with 'docker exec -it etl_run bash'\"; sleep 20; done"
    depends_on:
      - etl_kafka